Restructure for a standalone consul VM
Instead of co-hosting a 3-node consul cluster, run a single standalone
consul node. We're not testing consul here.

diff --git a/script/run-consul b/script/run-consul
--- a/script/run-consul
+++ b/script/run-consul
@@ -1,4 +1,6 @@
 #!/bin/bash
+#
+# Install containerised Consul as a system service.
 
 set -e
 
@@ -8,14 +10,74 @@ num_nodes=${#cluster_hostnames[@]}
 ip=$(avahi-resolve-host-name -4 "$(hostname -s).local" | cut -f2)
 leader_ip=$(avahi-resolve-host-name -4 "${cluster_hostnames[0]}.local" | cut -f2)
 
-echo "Starting consul on $ip with $num_nodes nodes, leader on $leader_ip"
-docker rm -f consul 2>&1 || true
-docker pull consul |cat
-docker run -d --name consul --net=host consul agent -server \
--bind="${ip}" \
--client=0.0.0.0 \
--bootstrap-expect="${num_nodes}" \
--retry-join="${leader_ip}"
+# Install our configuration.
+cat <<EOF >/etc/conf.d/consul
+CONSUL_LEADER_IP="${leader_ip}"
+CONSUL_NUM_NODES=$num_nodes
+EOF
+
+# Install our init script.
+cat <<'EOF' >/etc/init.d/consul
+#!/sbin/openrc-run
+
+set -e
+
+description="Consul service discovery and configuration"
+
+num_nodes="${CONSUL_NUM_NODES:?}"
+ip="$(avahi-resolve-host-name -4 "$(hostname -s).local" | cut -f2)"
+leader_ip="${CONSUL_LEADER_IP:?}"
+
+name="consul"
+command="/usr/bin/docker"
+command_args="run --name consul --net=host consul agent -server -bind=${ip} -client=0.0.0.0 -bootstrap-expect=${num_nodes} -retry-join=${leader_ip}"
+pidfile="/var/run/consul.pid"
+CONSUL_LOGFILE="${CONSUL_LOGFILE:-/var/log/$RC_SVCNAME.log}"
+CONSUL_ERRFILE="${CONSUL_ERRFILE:-${CONSUL_LOGFILE}}"
+CONSUL_OUTFILE="${CONSUL_OUTFILE:-${CONSUL_LOGFILE}}"
+start_stop_daemon_args="--background --stderr ${CONSUL_ERRFILE} --stdout ${CONSUL_OUTFILE}"
+
+depend() {
+	need docker
+	provide consul
+}
+
+stop() {
+	einfo "Stopping ${RC_SVCNAME} ..."
+	docker stop consul >/dev/null
+}
+
+exit_cleanup() {
+	exited="$(docker ps -a -q -f status=exited -f name=consul)"
+	if [ -n "$exited" ]; then
+		einfo "Removing old (exited) container"
+		docker rm "$exited" >/dev/null
+	fi
+}
+
+start_pre() {
+	exit_cleanup
+    docker pull consul | cat
+}
+
+stop_post() {
+	exit_cleanup
+}
+EOF
+
+# Install and start.
+chmod a+x /etc/init.d/consul
+rc-update add consul
+rc-service consul restart
+
+# echo "Starting consul on $ip with $num_nodes nodes, leader on $leader_ip"
+# docker rm -f consul 2>&1 || true
+# docker pull consul |cat
+# docker run -d --name consul --net=host consul agent -server \
+# -bind="${ip}" \
+# -client=0.0.0.0 \
+# -bootstrap-expect="${num_nodes}" \
+# -retry-join="${leader_ip}"
 
 sleep 2
 echo "Querying local consul agent"
diff --git a/script/run-storageos-plugin b/script/run-storageos-plugin
--- a/script/run-storageos-plugin
+++ b/script/run-storageos-plugin
@@ -9,8 +9,16 @@ else
 	shift
 fi
 
+if [ -z "$1" ]; then
+	kv_name="consul"
+else
+	kv_name="$1"
+	shift
+fi
+
 plugin=storageos/plugin
 ip=$(avahi-resolve-host-name -4 "$(hostname -s).local" | cut -f2)
+kv_ip=$(avahi-resolve-host-name -4 "${kv_name}.local" | cut -f2)
 
 # Don't recreate dir if it exists.  Consul will still have old id registered so
 # it needs to re-use same config for each run.
@@ -19,10 +27,32 @@ for dir in /var/lib/storageos; do
   [ -d $dir ] || mkdir -p $dir
 done
 
-# TODO: Move this to controlplane startup
-modprobe nbd nbds_max=1024 max_part=15
+# Set up nbd and autoload fuse. Note nbd isn't required, it just hugely improves
+# perforance.
+
+# Set options for nbd, the defaults aren't good enough for us.
+nbd_opts="nbds_max=1024 max_part=15"
+cat <<EOF >/etc/modprobe.d/storageos.conf
+options nbd $nbd_opts
+EOF
+
+# Set nbd and fuse to autoload.
+cat <<EOF >/etc/modules-load.d/storageos.conf
+nbd
+fuse
+EOF
+
+# Load now. Frustratingly, this won't use the options we set.
+# shellcheck disable=SC2086
+modprobe nbd $nbd_opts
 modprobe fuse
+
+# Check the options were correctly set.
+if [ "$(cat /sys/module/nbd/parameters/nbds_max)" -ne 1024 ]; then
+	echo "Failed to set nbd options correctly" >&2
+	exit 1
+fi
 
 echo "starting storageos plugin on $ip"
 docker plugin rm -f storageos 2>/dev/null || true
-docker plugin install --alias storageos --grant-all-permissions "$plugin:$version" ADVERTISE_IP="${ip}" KV_ADDR="${ip}"
+docker plugin install --alias storageos --grant-all-permissions "$plugin:$version" ADVERTISE_IP="${ip}" KV_ADDR="${kv_ip}"
